// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlyPJ9R_V7eIv6c7jrtSyKdxIltGbnq00',
    appId: '1:839781526307:web:af2928409fc356089aba96',
    messagingSenderId: '839781526307',
    projectId: 'alljob1',
    authDomain: 'alljob1.firebaseapp.com',
    storageBucket: 'alljob1.firebasestorage.app',
    measurementId: 'G-73TQ9JRJRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJsp6zfD5YD-pFHHIkKRHQfne_Pu0FC1s',
    // ⚠️ GÜNCELLENMESİ GEREKİYOR: paket adı com.sepettehizmet.app'e taşındı
    // (2026-08-01, yayın öncesi). Aşağıdaki appId hâlâ ESKİ com.ustasindan.app
    // kaydınındır. Firebase Console'da yeni Android app kaydı açılıp
    // google-services.json indirilince buradaki appId de onunla değiştirilmeli
    // (flutterfire configure bunu otomatik yapar).
    appId: '1:839781526307:android:53a729b742c6a8439aba96',
    messagingSenderId: '839781526307',
    projectId: 'alljob1',
    storageBucket: 'alljob1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5fwP1a7cFYTCP5uEdngeoYtY7VPBLLhM',
    appId: '1:839781526307:ios:a35b0070e8f483e59aba96',
    messagingSenderId: '839781526307',
    projectId: 'alljob1',
    storageBucket: 'alljob1.firebasestorage.app',
    // ⚠️ appId hâlâ ESKİ iOS kaydınındır (com.ustacepte.ustaCepte).
    // Xcode projesi com.sepettehizmet.app'e taşındı; Console'da yeni iOS app
    // kaydı açılıp GoogleService-Info.plist indirilince appId de yenilenmeli.
    iosBundleId: 'com.sepettehizmet.app',
  );
}
